project:
  type: website
  output-dir: docs

website:
  title: "Steven Meeks Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume

format:
  html:
    theme:
      - flatly
    css: styles.css
    toc: true



